name: Benchmark

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Run Benchmark
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
      with:
        elixir-version: '1.15.5'
        otp-version: '26.0.2'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Run
      run: elixir benchmark.exs
